# This file was generated by GoReleaser. DO NOT EDIT.
cask "cosy-posts" do
  name "cosy-posts"
  desc "Create a private online space to share photos, videos, audio and notes with a closed circle of friends."
  homepage "https://github.com/jphastings/cosy-posts"
  version "0.3.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cosy-posts"

  on_macos do
    on_intel do
      url "https://github.com/jphastings/cosy-posts/releases/download/v#{version}/cosy-posts_Darwin_x86_64.tar.gz",
        verified: "github.com/jphastings/cosy-posts"
      sha256 "5cc94b5d5fc3ac1e22421902463f42851cc805e9eee47c49525eccac84468e7b"
    end
    on_arm do
      url "https://github.com/jphastings/cosy-posts/releases/download/v#{version}/cosy-posts_Darwin_arm64.tar.gz",
        verified: "github.com/jphastings/cosy-posts"
      sha256 "84f0b29987eb3c0bcbc032937a0fc5b45d7d8c7bbb37140df229b58ef5d59895"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jphastings/cosy-posts/releases/download/v#{version}/cosy-posts_Linux_x86_64.tar.gz",
        verified: "github.com/jphastings/cosy-posts"
      sha256 "639c2499018ada9064f2ed446647c21422a350bf3f228e067a9883bd89d335dc"
    end
    on_arm do
      url "https://github.com/jphastings/cosy-posts/releases/download/v#{version}/cosy-posts_Linux_arm64.tar.gz",
        verified: "github.com/jphastings/cosy-posts"
      sha256 "cbb3ec6df63a0d7ef718ffefd3d6f63ff5b8ebee7c73abac36ee54876da97576"
    end
  end

  # No zap stanza required
end
