# This file was generated by GoReleaser. DO NOT EDIT.
cask "cosy-posts" do
  name "cosy-posts"
  desc "Create a private online space to share photos, videos, audio and notes with a closed circle of friends."
  homepage "https://github.com/jphastings/cosy-posts"
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cosy-posts"

  on_macos do
    on_intel do
      url "https://github.com/jphastings/cosy-posts/releases/download/v#{version}/cosy-posts_Darwin_x86_64.tar.gz",
        verified: "github.com/jphastings/cosy-posts"
      sha256 "9df90756bb549a2f05e53f7cdb3a3f38066659eaba9583f185d1ecd7a1dd85cc"
    end
    on_arm do
      url "https://github.com/jphastings/cosy-posts/releases/download/v#{version}/cosy-posts_Darwin_arm64.tar.gz",
        verified: "github.com/jphastings/cosy-posts"
      sha256 "5208a012b0c9037849317011e720d1f73b33e0218d0caf52160292aaf874a5e1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jphastings/cosy-posts/releases/download/v#{version}/cosy-posts_Linux_x86_64.tar.gz",
        verified: "github.com/jphastings/cosy-posts"
      sha256 "2f386c38a6bbfdb6eb2339e240ba5c1f380567826346da698278e0f205a8ec20"
    end
    on_arm do
      url "https://github.com/jphastings/cosy-posts/releases/download/v#{version}/cosy-posts_Linux_arm64.tar.gz",
        verified: "github.com/jphastings/cosy-posts"
      sha256 "e922cc0304ecea110bf0f2169205e90a074f7a06fce1b1c2d975f71743669de5"
    end
  end

  # No zap stanza required
end
