# This file was generated by GoReleaser. DO NOT EDIT.
cask "cosy-posts" do
  name "cosy-posts"
  desc "Create a private online space to share photos, videos, audio and notes with a closed circle of friends."
  homepage "https://github.com/jphastings/cosy-posts"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cosy-posts"

  on_macos do
    on_intel do
      url "https://github.com/jphastings/cosy-posts/releases/download/v#{version}/cosy-posts_Darwin_x86_64.tar.gz",
        verified: "github.com/jphastings/cosy-posts"
      sha256 "66436c1716e5937397ab8a634bf5833a4e84a0b6db483faa61d2e156eecc996a"
    end
    on_arm do
      url "https://github.com/jphastings/cosy-posts/releases/download/v#{version}/cosy-posts_Darwin_arm64.tar.gz",
        verified: "github.com/jphastings/cosy-posts"
      sha256 "e9e1e68bfb2448f9668b2de6a9528e9e86105f74566bbf9e0aafd0bdbee8d0f1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jphastings/cosy-posts/releases/download/v#{version}/cosy-posts_Linux_x86_64.tar.gz",
        verified: "github.com/jphastings/cosy-posts"
      sha256 "cc2b888287dd2a9df529f9d0c40b694fe94a1f50a954575c651639cd620e501d"
    end
    on_arm do
      url "https://github.com/jphastings/cosy-posts/releases/download/v#{version}/cosy-posts_Linux_arm64.tar.gz",
        verified: "github.com/jphastings/cosy-posts"
      sha256 "2e68686fb7333778271f4034f14ee0f3dd3879914fbfce68f802e381859a9bc8"
    end
  end

  # No zap stanza required
end
