# This file was generated by GoReleaser. DO NOT EDIT.
cask "emojify" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "73bed0380d5da2ea39bfd5f28e906074f4c99eeee5c87f5e40b9a2aec88b3538"
      url "https://github.com/jphastings/emojify/releases/download/v#{version}/emojify_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6f16485d5d81fab53d78803120ef115195ed97890fe5fedc6c5ddd13dbbcbdc8"
      url "https://github.com/jphastings/emojify/releases/download/v#{version}/emojify_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f3d1798570f7e23a8fa0dfa4d3fe18fefc8bd9f211a868c0fc6c5b8abd20d945"
      url "https://github.com/jphastings/emojify/releases/download/v#{version}/emojify_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c51cad96694dd7d1eaf07c7e1e30e7edb48aac28767864285a92a813136c61cd"
      url "https://github.com/jphastings/emojify/releases/download/v#{version}/emojify_#{version}_linux_amd64.tar.gz"
    end
  end

  name "emojify"
  desc "Pick the most relevant emoji for a small length of text"
  homepage "https://github.com/jphastings/emojify"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emojify"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/emojify"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    For the larger embedding model, and to run this as a server:
      docker run -p 8080:8080 ghcr.io/jphastings/emojify
  EOS
end
