# This file was generated by GoReleaser. DO NOT EDIT.
cask "emojify" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "226e4c4a84c6c71a72141f55cad11c3d3215c4542a0933b146c6e6a8aa090ab2"
      url "https://github.com/jphastings/emojify/releases/download/v#{version}/emojify_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a8d34e082bf1cee17decc0356492040314b894199a5ca7a29272e634ee20f36d"
      url "https://github.com/jphastings/emojify/releases/download/v#{version}/emojify_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b775d490d853d2f36df8beefbae08465abf09df59682af90483986fd83c25c91"
      url "https://github.com/jphastings/emojify/releases/download/v#{version}/emojify_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "36dca2d50388f17232058d1a3d31342c34a09c1bf3ff1c70e0dee53302fe3612"
      url "https://github.com/jphastings/emojify/releases/download/v#{version}/emojify_#{version}_linux_amd64.tar.gz"
    end
  end

  name "emojify"
  desc "Pick the most relevant emoji for a small length of text"
  homepage "https://github.com/jphastings/emojify"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emojify"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/emojify"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Uses a small built-in embedding model by default. `brew install onnxruntime`
    unlocks substantially better matches automatically — no further setup needed.
    To run this as a server instead: docker run -p 8080:8080 ghcr.io/jphastings/emojify
  EOS
end
