# This file was generated by GoReleaser. DO NOT EDIT.
cask "postcards" do
  version "0.27.0"

  on_macos do
    on_intel do
      sha256 "774545d07932c87bad2fdc725034c9bac3549093876e08b7d61a2c3e61148499"
      url "https://github.com/jphastings/dotpostcard/releases/download/v#{version}/dotpostcard_Darwin_x86_64.tar.gz",
        verified: "github.com/jphastings/dotpostcard"
    end
    on_arm do
      sha256 "120687bf35980bf81b71b3d250539500f2ad5273b0a6895fe1ec563b9353c751"
      url "https://github.com/jphastings/dotpostcard/releases/download/v#{version}/dotpostcard_Darwin_arm64.tar.gz",
        verified: "github.com/jphastings/dotpostcard"
    end
  end

  on_linux do
    on_intel do
      sha256 "b8cf165f8d3e9bdc3c97b227dfbec2e66f605578fcf0acfb7622ba1a299d5e34"
      url "https://github.com/jphastings/dotpostcard/releases/download/v#{version}/dotpostcard_Linux_x86_64.tar.gz",
        verified: "github.com/jphastings/dotpostcard"
    end
    on_arm do
      sha256 "de6d9e0fc27b833296b284221d6b866d6fd762598031d8437bc90da249aa4ed5"
      url "https://github.com/jphastings/dotpostcard/releases/download/v#{version}/dotpostcard_Linux_arm64.tar.gz",
        verified: "github.com/jphastings/dotpostcard"
    end
  end

  name "postcards"
  desc "Tool for creating digital versions of physical postcards"
  homepage "https://dotpostcard.org/cli/postcards"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "postcards"

  # No zap stanza required

end
