# This file was generated by GoReleaser. DO NOT EDIT.
cask "postcards" do
  version "0.32.0"

  on_macos do
    on_arm do
      sha256 "8aec4ddd761fa962e782cc0a1f37914608ee7495384a14a69fa8b020df3de720"
      url "https://github.com/jphastings/dotpostcard/releases/download/v#{version}/dotpostcard_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7721f28611a638624f962e41e8ba39a9f4c6b58c7052dd424acf549581410296"
      url "https://github.com/jphastings/dotpostcard/releases/download/v#{version}/dotpostcard_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "da1418fee56c508a9ec7d466ca4653f85e63b71ee4fda730b582dccfc0e6e88b"
      url "https://github.com/jphastings/dotpostcard/releases/download/v#{version}/dotpostcard_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e567fa853e23650f64f9f4a625d78de34359324ea1c7fc3743a29d5e8ba920ea"
      url "https://github.com/jphastings/dotpostcard/releases/download/v#{version}/dotpostcard_Linux_x86_64.tar.gz"
    end
  end

  name "postcards"
  desc "Tool for creating digital versions of physical postcards"
  homepage "https://dotpostcard.org/cli/postcards"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "postcards"

  # No zap stanza required
end
