# This file was generated by GoReleaser. DO NOT EDIT.
cask "postcards" do
  version "0.29.0"

  on_macos do
    on_arm do
      sha256 "41dd4a6c56b0de9690602f86f0eb5f7967a85ffa6c2e8c752d81561af6384923"
      url "https://github.com/jphastings/dotpostcard/releases/download/v#{version}/dotpostcard_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "aead62c76b2f195e0d7a621a6f6a2c460b7aa36ffd1d0d6ed180caf2684273d2"
      url "https://github.com/jphastings/dotpostcard/releases/download/v#{version}/dotpostcard_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "28d14302f8525c4636160a52041ab5b247d9b5d4b00d95b47c2793ec34324e9c"
      url "https://github.com/jphastings/dotpostcard/releases/download/v#{version}/dotpostcard_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6af8b6d1fc4196ef98d8fca13ac4a2ec0c7d5891f6d64198c82c6d4d38db05f1"
      url "https://github.com/jphastings/dotpostcard/releases/download/v#{version}/dotpostcard_Linux_x86_64.tar.gz"
    end
  end

  name "postcards"
  desc "Tool for creating digital versions of physical postcards"
  homepage "https://dotpostcard.org/cli/postcards"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "postcards"

  # No zap stanza required
end
