# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jpegli < Formula
  desc "Optionless image size & dimension reduction using JPEGli."
  homepage "https://github.com/jphastings/jpegli/"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jphastings/jpegli/releases/download/v0.1.1/jpegli_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "43d474057452f3f0507fddd4e68651ba3678805acf77e265f16c8aa38c4891df"

      def install
        bin.install "jpegli"
      end
    end
    on_arm do
      url "https://github.com/jphastings/jpegli/releases/download/v0.1.1/jpegli_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4d1e3637f74c6dde3d6ec2db6c14429c84942c8ee190d214407a80654f65ec09"

      def install
        bin.install "jpegli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jphastings/jpegli/releases/download/v0.1.1/jpegli_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "501ed01f5f61bef95ff3903d4233618e20f8153a56d0b9b152f2c6fe2c1edaaf"

        def install
          bin.install "jpegli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jphastings/jpegli/releases/download/v0.1.1/jpegli_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "0f61bd1792fdb07dba8c98015c79dd8b2148dae39503e169992f5bca1b47325c"

        def install
          bin.install "jpegli"
        end
      end
    end
  end
end
