# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jwker < Formula
  desc "Easily convert between PEM and JWK files."
  homepage "https://github.com/jphastings/jwker/"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jphastings/jwker/releases/download/v0.2.2/jwker_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "1c0ce45bcd9d749aeb4f34e9c0eef879e708d912a64b6d33cdacde4bf73cf34f"

      def install
        bin.install "jwker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jphastings/jwker/releases/download/v0.2.2/jwker_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0e62380b177e60bcdaff2253e3faf516ad1f0cb8a91334ed5a5ccedc8f3cd421"

      def install
        bin.install "jwker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jphastings/jwker/releases/download/v0.2.2/jwker_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "f94e8cacbc710c3a9a978604cdf9a67bba758bef2f300284714952d0ecc5e7f4"
      def install
        bin.install "jwker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jphastings/jwker/releases/download/v0.2.2/jwker_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e3cac2ee4a82136d2a13b77ea2f8beb5e4cd90e253638005cbd431d2e2d09bde"
      def install
        bin.install "jwker"
      end
    end
  end

  resource("testdata.pem") do
    url "https://raw.githubusercontent.com/jphastings/jwker/main/test_data/x25519.pem"
    sha256 "546a61cc1eb31e336be056bde9ed1ad417f09fde3beb551f24406b043b5ce69a"
  end
  resource("testdata.jwk") do
    url "https://raw.githubusercontent.com/jphastings/jwker/main/test_data/x25519.jwk"
    sha256 "f8d83d7dc2f1b6e4d6e4869b75352660e1f35619b96a2b3efa01648ea428903d"
  end

  test do
    resource("testdata.pem").stage do
      resource("testdata.jwk").stage do
        assert_match File.read("testdata.jwk"), shell_output("#{bin}/jwker testdata.pem")
      end
    end
  end
end
