# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PkdnsVanity < Formula
  desc "Generate vanity PKDNS domain names"
  homepage "https://github.com/jphastings/pkdns-vanity"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jphastings/pkdns-vanity/releases/download/1.1.0/pkdns-vanity_Darwin_x86_64.tar.gz"
      sha256 "acde2581b5a604a2e167fab19bbac62d51f7b683da76a442b511c8ef51a06282"

      def install
        bin.install "pkdns-vanity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jphastings/pkdns-vanity/releases/download/1.1.0/pkdns-vanity_Darwin_arm64.tar.gz"
      sha256 "d9d98492691141d946321d66494b884d6106db4ca51fa0d3b835006e8abedc16"

      def install
        bin.install "pkdns-vanity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jphastings/pkdns-vanity/releases/download/1.1.0/pkdns-vanity_Linux_x86_64.tar.gz"
        sha256 "cfeed1ae89f80d0c08b5be962fb7bf0d95b126f197223fd688e14859eab9d7ca"

        def install
          bin.install "pkdns-vanity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jphastings/pkdns-vanity/releases/download/1.1.0/pkdns-vanity_Linux_arm64.tar.gz"
        sha256 "5d4855a77ffb2e57a75a686465713d86d499e0fb69430a0d1f8c1b287daa4b25"

        def install
          bin.install "pkdns-vanity"
        end
      end
    end
  end
end
