# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Postcards < Formula
  desc "Tool for creating digital versions of physical postcards"
  homepage "https://dotpostcards.org/cli/postcards"
  version "0.15.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jphastings/dotpostcard/releases/download/v0.15.5/dotpostcard_Darwin_x86_64.tar.gz"
      sha256 "2dce2967385597dea35a49071fe94a6350535f66691413118ba961749e0d704c"

      def install
        bin.install "postcards"
        bin.install "postoffice"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jphastings/dotpostcard/releases/download/v0.15.5/dotpostcard_Darwin_arm64.tar.gz"
      sha256 "1366581333bff1a6371101c5c109ea1c7dac6be09126054fcd42cf5c5803abf2"

      def install
        bin.install "postcards"
        bin.install "postoffice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jphastings/dotpostcard/releases/download/v0.15.5/dotpostcard_Linux_x86_64.tar.gz"
      sha256 "8e4042acf6aa8083a36b286597f428387264cde1a41ef24936af621802f8bb57"
      def install
        bin.install "postcards"
        bin.install "postoffice"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jphastings/dotpostcard/releases/download/v0.15.5/dotpostcard_Linux_arm64.tar.gz"
      sha256 "9ded6b02a6a0f893aa2f2fdf5d5146aa8fca01fec6775d68d11cb361ad3e30ef"
      def install
        bin.install "postcards"
        bin.install "postoffice"
      end
    end
  end

  test do
    resource("hello.postcard").stage do
      expected_start = "Convert digital representations of postcards between various formats.\n"
      actual_output = shell_output("#{bin}/postcards help")
      assert actual_output.start_with?(expected_start)
    end
  end
end
