# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Postcards < Formula
  desc "Tool for creating digital versions of physical postcards"
  homepage "https://dotpostcards.org/cli/postcards"
  version "0.11.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jphastings/dotpostcard/releases/download/0.11.2/dotpostcard_Darwin_x86_64.tar.gz"
      sha256 "2d8a0b03e7a7d910e409bd70251cb3794de4b8e0502114c458ea5d4c5f36ae63"

      def install
        bin.install "postcards"
        bin.install "postoffice"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jphastings/dotpostcard/releases/download/0.11.2/dotpostcard_Darwin_arm64.tar.gz"
      sha256 "c0f3644a0632e36954fd84b44d8e52a2c6c2014158e3ad4f2a8d36d9191ea034"

      def install
        bin.install "postcards"
        bin.install "postoffice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jphastings/dotpostcard/releases/download/0.11.2/dotpostcard_Linux_x86_64.tar.gz"
        sha256 "e75d890f4e996ddf2754e032369e03baa09c695b46dbd727753555b856a15a9d"

        def install
          bin.install "postcards"
          bin.install "postoffice"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jphastings/dotpostcard/releases/download/0.11.2/dotpostcard_Linux_arm64.tar.gz"
        sha256 "0b66c30f6a91ba7bd20a0da41112d03917ca04b43a921d4421c0d7b0d35d7f94"

        def install
          bin.install "postcards"
          bin.install "postoffice"
        end
      end
    end
  end

  test do
    resource("hello.postcard").stage do
      expected_start = "Convert digital representations of postcards between various formats.\n"
      actual_output = shell_output("#{bin}/postcards help")
      assert actual_output.start_with?(expected_start)
    end
  end
end
