# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Postcards < Formula
  desc "Tool for creating digital versions of physical postcards"
  homepage "https://dotpostcards.org/cli/postcards"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jphastings/dotpostcard/releases/download/0.7.2/dotpostcard_Darwin_x86_64.tar.gz"
      sha256 "bce2b610fc3a37aed7fd2049e3b7c1395a22eba48fef7789c8df64995bca827c"

      def install
        bin.install "postcards"
        bin.install "postoffice"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jphastings/dotpostcard/releases/download/0.7.2/dotpostcard_Darwin_arm64.tar.gz"
      sha256 "b2a910479c281634ec19c8c4c4a49c86dd3b6893e398f848ccfd52da61fbcba6"

      def install
        bin.install "postcards"
        bin.install "postoffice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jphastings/dotpostcard/releases/download/0.7.2/dotpostcard_Linux_x86_64.tar.gz"
        sha256 "57e1ff48525c6850d0bf06ab6f43fc2efbfa5ec0e7782046c1eca9052d168d02"

        def install
          bin.install "postcards"
          bin.install "postoffice"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jphastings/dotpostcard/releases/download/0.7.2/dotpostcard_Linux_arm64.tar.gz"
        sha256 "6fe51e9da1a983e7b2ddfb8bad608e594eea4da2ede402bc2f7ef23fbc6d84ea"

        def install
          bin.install "postcards"
          bin.install "postoffice"
        end
      end
    end
  end

  test do
    resource("hello.postcard").stage do
      expected_start = "Convert digital representations of postcards between various formats.\n"
      actual_output = shell_output("#{bin}/postcards help")
      assert actual_output.start_with?(expected_start)
    end
  end
end
